
import { GoogleGenAI, LiveServerMessage, Modality, Blob, Chat, Part } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

// FIX: The `LiveSession` type is not exported from "@google/genai".
// It is inferred from the return type of `ai.live.connect` to ensure type safety.
export type LiveSession = Awaited<ReturnType<typeof ai.live.connect>>;

export async function fileToGenerativePart(file: File) {
  const base64EncodedDataPromise = new Promise((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve((reader.result as string).split(',')[1]);
    reader.readAsDataURL(file);
  });
  return {
    inlineData: {
      data: await base64EncodedDataPromise,
      mimeType: file.type,
    },
  };
}

export const generateImage = async (prompt: string): Promise<string> => {
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/png',
          aspectRatio: '1:1',
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
        const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
        return `data:image/png;base64,${base64ImageBytes}`;
    } else {
        throw new Error("No image was generated by the API.");
    }
};

export const startChat = (systemInstruction: string, model: string = 'gemini-3-flash-preview', config: Record<string, unknown> = {}): Chat => {
  const chat = ai.chats.create({
    model: model,
    config: {
      ...config,
      systemInstruction,
    },
  });
  return chat;
};

export const generateOneOffContentStream = async (
    text: string, 
    attachmentFile: File | null,
    systemInstruction: string,
    model: string = 'gemini-3-flash-preview',
    config: Record<string, unknown> = {}
) => {
    const parts: Part[] = [];
    if (attachmentFile) {
        parts.push(await fileToGenerativePart(attachmentFile));
    }
    if (text.trim()) {
        parts.push({text});
    }

    if (parts.length === 0) return null;

    const result = await ai.models.generateContentStream({
        model: model,
        contents: { parts },
        config: {
          ...config,
          systemInstruction: systemInstruction
        }
    });

    return result;
};

export const generateJsonContent = async (prompt: string, schema: Record<string, unknown>, model: string = 'gemini-3-flash-preview') => {
    const response = await ai.models.generateContent({
        model: model,
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: schema,
        },
    });

    try {
        const jsonText = response.text.trim();
        return JSON.parse(jsonText);
    } catch {
        console.error("Failed to parse JSON response:", response.text);
        throw new Error("Invalid JSON response from model.");
    }
};


// --- Live Session Service ---

function encode(bytes: Uint8Array) {
    let binary = '';
    const len = bytes.byteLength;
    for (let i = 0; i < len; i++) {
        binary += String.fromCharCode(bytes[i]);
    }
    return btoa(binary);
}

// FIX: Export decode function for use in AppContext.
export function decode(base64: string) {
    const binaryString = atob(base64);
    const len = binaryString.length;
    const bytes = new Uint8Array(len);
    for (let i = 0; i < len; i++) {
        bytes[i] = binaryString.charCodeAt(i);
    }
    return bytes;
}

// FIX: Add and export custom decodeAudioData function as per Gemini API guidelines.
// The native AudioContext.decodeAudioData is not suitable for raw PCM streams.
export async function decodeAudioData(
  data: Uint8Array,
  ctx: AudioContext,
  sampleRate: number,
  numChannels: number,
): Promise<AudioBuffer> {
  const dataInt16 = new Int16Array(data.buffer);
  const frameCount = dataInt16.length / numChannels;
  const buffer = ctx.createBuffer(numChannels, frameCount, sampleRate);

  for (let channel = 0; channel < numChannels; channel++) {
    const channelData = buffer.getChannelData(channel);
    for (let i = 0; i < frameCount; i++) {
      channelData[i] = dataInt16[i * numChannels + channel] / 32768.0;
    }
  }
  return buffer;
}

export function createBlob(data: Float32Array): Blob {
    const l = data.length;
    const int16 = new Int16Array(l);
    for (let i = 0; i < l; i++) {
        // Clamp the value to the [-1.0, 1.0] range to prevent overflow/clipping.
        const val = Math.max(-1.0, Math.min(1.0, data[i]));
        // Convert the float to a 16-bit signed integer.
        int16[i] = val < 0 ? val * 32768 : val * 32767;
    }
    return {
        data: encode(new Uint8Array(int16.buffer)),
        mimeType: 'audio/pcm;rate=16000',
    };
}


interface ConnectLiveSessionParams {
    systemInstruction: string;
    onMessage: (message: LiveServerMessage) => void;
    onError: (error: ErrorEvent) => void;
    onClose: (event: CloseEvent) => void;
}

export const connectLiveSession = async ({
    systemInstruction,
    onMessage,
    onError,
    onClose,
}: ConnectLiveSessionParams): Promise<LiveSession> => {

    const sessionPromise = ai.live.connect({
        model: 'gemini-2.5-flash-native-audio-preview-09-2025',
        callbacks: {
            onopen: () => console.log('Live session opened'),
            onmessage: (message: LiveServerMessage) => {
                onMessage(message);
            },
            onerror: onError,
            onclose: onClose,
        },
        config: {
            responseModalities: [Modality.AUDIO],
            speechConfig: {
                voiceConfig: { prebuiltVoiceConfig: { voiceName: 'Zephyr' } },
            },
            inputAudioTranscription: {},
            outputAudioTranscription: {},
            systemInstruction: systemInstruction,
        },
    });

    return sessionPromise;
};
