import { GoogleGenAI, LiveServerMessage, Blob } from "@google/genai";
import { LIVE_MODEL, liveConnectConfig } from "../constants/liveSession";

const API = {
  stream: "/api/gemini/stream",
  image: "/api/gemini/image",
  json: "/api/gemini/json",
  liveToken: "/api/gemini/live-token",
};

const MAX_HISTORY = 40;
const GENERIC_ERROR = "Could not retrieve response from the model.";

type ChatPart = { text: string } | { inlineData: { data: string; mimeType: string } };
type ChatContent = { role: "user" | "model"; parts: ChatPart[] };

export interface HikaruChat {
  sendMessageStream(params: { message: ChatPart[] }): Promise<AsyncIterable<{ text?: string }>>;
}

async function readError(response: Response): Promise<string> {
  try {
    const data = await response.json();
    if (data && typeof data.error === "string" && data.error.length > 0 && data.error.length < 200) {
      return data.error;
    }
  } catch {
    // The body was not the sanitized error contract.
  }
  return GENERIC_ERROR;
}

async function postJson(path: string, body: unknown): Promise<Response> {
  return fetch(path, {
    method: "POST",
    cache: "no-store",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(body),
  });
}

async function* streamEvents(response: Response): AsyncGenerator<{ text?: string }> {
  if (!response.body) throw new Error(GENERIC_ERROR);
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  const consume = function* (block: string): Generator<{ text?: string }> {
    const line = block
      .split("\n")
      .map((entry) => entry.trim())
      .find((entry) => entry.startsWith("data:"));
    if (!line) return;
    const raw = line.slice(line.indexOf(":") + 1).trim();
    if (!raw) return;
    let payload: { text?: unknown; error?: unknown; done?: unknown };
    try {
      payload = JSON.parse(raw);
    } catch {
      throw new Error(GENERIC_ERROR);
    }
    if (typeof payload.error === "string") {
      throw new Error(payload.error.length < 200 ? payload.error : GENERIC_ERROR);
    }
    if (payload.done === true) return;
    if (typeof payload.text === "string" && payload.text) yield { text: payload.text };
  };

  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true }).replace(/\r\n/g, "\n");
    const blocks = buffer.split("\n\n");
    buffer = blocks.pop() ?? "";
    for (const block of blocks) yield* consume(block);
  }
  buffer += decoder.decode();
  if (buffer.trim()) yield* consume(buffer);
}

export async function fileToGenerativePart(file: File): Promise<{ inlineData: { data: string; mimeType: string } }> {
  const data = await new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(new Error("Could not read the attachment."));
    reader.onloadend = () => {
      const result = reader.result;
      if (typeof result !== "string") {
        reject(new Error("Could not read the attachment."));
        return;
      }
      const encoded = result.split(",")[1];
      if (!encoded) {
        reject(new Error("Could not read the attachment."));
        return;
      }
      resolve(encoded);
    };
    reader.readAsDataURL(file);
  });
  return {
    inlineData: {
      data,
      mimeType: file.type,
    },
  };
}

export const generateImage = async (prompt: string): Promise<string> => {
  const response = await postJson(API.image, { prompt });
  if (!response.ok) throw new Error(await readError(response));
  const data = await response.json();
  if (typeof data.image !== "string" || !data.image.startsWith("data:image/")) {
    throw new Error("No image was generated by the API.");
  }
  return data.image;
};

export const startChat = (
  systemInstruction: string,
  model: string,
  config: { thinkingConfig?: { thinkingBudget?: number } } = {},
): HikaruChat => {
  const history: ChatContent[] = [];
  const thinkingBudget = config.thinkingConfig?.thinkingBudget;

  return {
    async sendMessageStream({ message }) {
      const contents = [...history, { role: "user" as const, parts: message }];
      const response = await postJson(API.stream, {
        model,
        systemInstruction,
        ...(typeof thinkingBudget === "number" ? { thinkingBudget } : {}),
        contents,
      });
      if (!response.ok) throw new Error(await readError(response));

      let fullText = "";
      const source = streamEvents(response);
      async function* iterate() {
        for await (const event of source) {
          if (event.text) fullText += event.text;
          yield event;
        }
        history.push({ role: "user", parts: message });
        history.push({ role: "model", parts: [{ text: fullText }] });
        if (history.length > MAX_HISTORY) history.splice(0, history.length - MAX_HISTORY);
      }
      return iterate();
    },
  };
};

export const generateOneOffContentStream = async (
  text: string,
  attachmentFile: File | null,
  systemInstruction: string,
  model: string,
  config: { thinkingConfig?: { thinkingBudget?: number } } = {},
) => {
  const parts: ChatPart[] = [];
  if (attachmentFile) {
    parts.push(await fileToGenerativePart(attachmentFile));
  }
  if (text.trim()) {
    parts.push({ text });
  }
  if (parts.length === 0) return null;

  const thinkingBudget = config.thinkingConfig?.thinkingBudget;
  const response = await postJson(API.stream, {
    model,
    systemInstruction,
    ...(typeof thinkingBudget === "number" ? { thinkingBudget } : {}),
    contents: [{ role: "user", parts }],
  });
  if (!response.ok) throw new Error(await readError(response));
  return streamEvents(response);
};

export const generateJsonContent = async (prompt: string, schema: unknown, model: string) => {
  const response = await postJson(API.json, { prompt, schema, model });
  if (!response.ok) throw new Error(await readError(response));
  const data = await response.json();
  if (!data || typeof data.result !== "object" || data.result === null || Array.isArray(data.result)) {
    throw new Error("Invalid JSON response from model.");
  }
  return data.result as { scenarios?: Array<{ title: string; probability: number; analysis: string }> };
};

function encode(bytes: Uint8Array) {
  let binary = "";
  const len = bytes.byteLength;
  for (let i = 0; i < len; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

export function decode(base64: string) {
  const binaryString = atob(base64);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

export async function decodeAudioData(
  data: Uint8Array,
  ctx: AudioContext,
  sampleRate: number,
  numChannels: number,
): Promise<AudioBuffer> {
  const dataInt16 = new Int16Array(data.buffer);
  const frameCount = dataInt16.length / numChannels;
  const buffer = ctx.createBuffer(numChannels, frameCount, sampleRate);

  for (let channel = 0; channel < numChannels; channel++) {
    const channelData = buffer.getChannelData(channel);
    for (let i = 0; i < frameCount; i++) {
      channelData[i] = dataInt16[i * numChannels + channel] / 32768.0;
    }
  }
  return buffer;
}

export function createBlob(data: Float32Array): Blob {
  const l = data.length;
  const int16 = new Int16Array(l);
  for (let i = 0; i < l; i++) {
    const val = Math.max(-1.0, Math.min(1.0, data[i]));
    int16[i] = val < 0 ? val * 32768 : val * 32767;
  }
  return {
    data: encode(new Uint8Array(int16.buffer)),
    mimeType: "audio/pcm;rate=16000",
  };
}

interface ConnectLiveSessionParams {
  onMessage: (message: LiveServerMessage) => void;
  onError: (error: ErrorEvent) => void;
  onClose: (event: CloseEvent) => void;
}

export const connectLiveSession = async ({
  onMessage,
  onError,
  onClose,
}: ConnectLiveSessionParams) => {
  const response = await fetch(API.liveToken, {
    method: "POST",
    cache: "no-store",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: "{}",
  });
  if (!response.ok) throw new Error(await readError(response));
  const data = await response.json();
  if (!data || typeof data.token !== "string" || data.token.length === 0) {
    throw new Error("Could not start the live session.");
  }

  const ai = new GoogleGenAI({
    apiKey: data.token,
    httpOptions: { apiVersion: "v1alpha" },
  });
  return ai.live.connect({
    model: LIVE_MODEL,
    callbacks: {
      onopen: () => console.log("Live session opened"),
      onmessage: (message: LiveServerMessage) => {
        onMessage(message);
      },
      onerror: () => {
        onError(new ErrorEvent("error"));
      },
      onclose: onClose,
    },
    config: liveConnectConfig,
  });
};

export type LiveSession = Awaited<ReturnType<typeof connectLiveSession>>;
